mysql:
  host: "localhost"
  user: "root"
  password: "adam@KIRA98"
  database: "email_recavaring"

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"

paths:
  sql_script: "MAIN TABLE.sql"
  csv_output_directory: "directory/"

default:
  email: "default@gmail.com"
  phone_number: "00000000"
  dob: "1970-01-01"

etl:
  chunk_number: 6
  total_size: 9000  # Example value, to be updated based on the actual size of your dataset
  processes: 3
